export enum LoginResponseStatus{
    LOGIN_SUCCESS ="LOGIN_SUCCESS",
    INVALID_USERNAME = "INVALID_USERNAME",
    INVALID_PASSWORD = "INVALID_PASSWORD"
}

export enum ChangePasswordResponse{
    PASSWORD_CHANGED_FAILED = "PASSWORD_CHANGED_FAILED",
    PASSWORD_CHANGED_SUCESSFUL = "PASSWORD_CHANGED_SUCESSFUL",
    INVALID_EMPLOYEE = "INVALID_EMPLOYEE"
}